### ISSUE TITLE
Bad performance on multivariable functions.

### ISSUE THREAD

**Issue by adamczykm** [timholy/FastAnonymous.jl#2]
Have a look:
a=randn(5000000);

@time(reduce((x,y) -> x,a))
elapsed time: 0.250185444 seconds (60000812 bytes allocated, 51.42% gc time)
0.5564212271634134

@time(reduce(@anon((x,y) -> x),a))
elapsed time: 0.815615445 seconds (120012708 bytes allocated, 35.23% gc time)
0.5564212271634134

**Comment by timholy** [comment]
This is fixed in julia 0.4 because of https://github.com/JuliaLang/julia/pull/10314. I'll close the issue, but note that on the 0.3 version of this package it would still require a pull request to implement efficient `reduce`. If you decide to do this, I can create a 0.3 branch; as it is, further development of this package on 0.3 is frozen.
